// AUTO-PORTED from a-decade-apart/content/audio-manifest.js — only the entries
// referenced by chapter1 (the rest of the chapters are Phase 2+). Text -> compiled
// require() reference, since RN cannot fetch a runtime string path like the web
// version does (see a-decade-apart/main.js playAudio()).
export const audioManifest: Record<string, number> = {
  'Hello! Passport, please.': require('../assets/audio/hello-passport-please-deca7216.m4a'),
  'Here you are.': require('../assets/audio/here-you-are-57403500.m4a'),
  'Nice to meet you.': require('../assets/audio/nice-to-meet-you-67bd7ea9.m4a'),
  'What\'s the purpose of your visit?': require('../assets/audio/what-s-the-purpose-of-your-visit-7d58f7b0.m4a'),
  'I\'m here to meet someone.': require('../assets/audio/i-m-here-to-meet-someone-419af4d6.m4a'),
  'Goodbye.': require('../assets/audio/goodbye-0101977b.m4a'),
  'Interesting! Welcome to Toronto.': require('../assets/audio/interesting-welcome-to-toronto-9a1c64ce.m4a'),
  'Thank you!': require('../assets/audio/thank-you-498cd895.m4a'),
  'Sorry.': require('../assets/audio/sorry-ed2916ed.m4a'),
  'Hop in! Where to?': require('../assets/audio/hop-in-where-to-5cdb7037.m4a'),
  'This address, please.': require('../assets/audio/this-address-please-5a1649b7.m4a'),
  'I am fine, thanks.': require('../assets/audio/i-am-fine-thanks-93bd30ad.m4a'),
  'Huh, that\'s an old street. Haven\'t heard that name in years.': require('../assets/audio/huh-that-s-an-old-street-haven-t-heard-t-9094c944.m4a'),
  'Really? Do you know it well?': require('../assets/audio/really-do-you-know-it-well-b55f487a.m4a'),
  'I don\'t know.': require('../assets/audio/i-don-t-know-5e5684b8.m4a'),
  'We\'re here!': require('../assets/audio/we-re-here-764fb99c.m4a'),
  'Perfect, this is it.': require('../assets/audio/perfect-this-is-it-8a30cffa.m4a'),
  'Where are we?': require('../assets/audio/where-are-we-88147f84.m4a'),
  'Welcome! Do you have a reservation?': require('../assets/audio/welcome-do-you-have-a-reservation-cf8887bf.m4a'),
  'Yes, under Zhang.': require('../assets/audio/yes-under-zhang-897e3162.m4a'),
  'No, thank you.': require('../assets/audio/no-thank-you-72521a14.m4a'),
  'Actually — someone left this here for you, years ago.': require('../assets/audio/actually-someone-left-this-here-for-you--ae83eaed.m4a'),
  'For me? Can I see it?': require('../assets/audio/for-me-can-i-see-it-45bd2a3a.m4a'),
  'I have no money.': require('../assets/audio/i-have-no-money-a8f1bd60.m4a'),
  'Here you go. It\'s a note from a woman named Emma.': require('../assets/audio/here-you-go-it-s-a-note-from-a-woman-nam-18840238.m4a'),
  'Thank you so much!': require('../assets/audio/thank-you-so-much-422f6774.m4a'),
  'Morning! What can I get for you?': require('../assets/audio/morning-what-can-i-get-for-you-4b20bb7f.m4a'),
  'A coffee and a croissant, please.': require('../assets/audio/a-coffee-and-a-croissant-please-f0040c9c.m4a'),
  'I\'m not hungry.': require('../assets/audio/i-m-not-hungry-4012e532.m4a'),
  'Wait — is that Emma\'s note? I know her!': require('../assets/audio/wait-is-that-emma-s-note-i-know-her-abe46368.m4a'),
  'You know her? Where is she?': require('../assets/audio/you-know-her-where-is-she-ccd33841.m4a'),
  'She said... watch the sunset from the CN Tower.': require('../assets/audio/she-said-watch-the-sunset-from-the-cn-to-6933ce0e.m4a'),
  'Thank you, I\'m on my way!': require('../assets/audio/thank-you-i-m-on-my-way-5d074a39.m4a'),
  'Is it free?': require('../assets/audio/is-it-free-c1b1d482.m4a'),
  'Yes? Can I help you?': require('../assets/audio/yes-can-i-help-you-cf0727a7.m4a'),
  'Excuse me, where is the CN Tower?': require('../assets/audio/excuse-me-where-is-the-cn-tower-a02608b1.m4a'),
  'I like pizza.': require('../assets/audio/i-like-pizza-314720fd.m4a'),
  'Go straight, then turn left.': require('../assets/audio/go-straight-then-turn-left-cacd2355.m4a'),
  'Turn left? Do you mean at the light?': require('../assets/audio/turn-left-do-you-mean-at-the-light-119dc10c.m4a'),
  'Turn right?': require('../assets/audio/turn-right-cae9046b.m4a'),
  'Hurry, the sun is setting!': require('../assets/audio/hurry-the-sun-is-setting-431ed552.m4a'),
  'Thank you, I\'m running!': require('../assets/audio/thank-you-i-m-running-a781b496.m4a'),
  'Too far.': require('../assets/audio/too-far-a7efed4b.m4a'),
  'Excuse me — are you looking for someone?': require('../assets/audio/excuse-me-are-you-looking-for-someone-8cffa992.m4a'),
  'Yes! Do you know Emma?': require('../assets/audio/yes-do-you-know-emma-0e3878c8.m4a'),
  'I live here.': require('../assets/audio/i-live-here-46c94c44.m4a'),
  'I\'m her brother. She asked me to wait for you.': require('../assets/audio/i-m-her-brother-she-asked-me-to-wait-for-5a7d2e0c.m4a'),
  'Can you tell me where she is?': require('../assets/audio/can-you-tell-me-where-she-is-4de147cf.m4a'),
  'She\'s running late — meet her for dinner instead. Here\'s the address.': require('../assets/audio/she-s-running-late-meet-her-for-dinner-i-8accaf66.m4a'),
  'Sure, I\'ll see you there.': require('../assets/audio/sure-i-ll-see-you-there-4a6ded56.m4a'),
  'No, never.': require('../assets/audio/no-never-27179f5c.m4a'),
  'Welcome! Table for two?': require('../assets/audio/welcome-table-for-two-d71bb93c.m4a'),
  'Yes, table for two.': require('../assets/audio/yes-table-for-two-80d6d950.m4a'),
  'I\'m alone.': require('../assets/audio/i-m-alone-84f08e63.m4a'),
  'Ten years... you actually came.': require('../assets/audio/ten-years-you-actually-came-e31b1d88.m4a'),
  'Of course. A promise is a promise.': require('../assets/audio/of-course-a-promise-is-a-promise-5c699770.m4a'),
  'Nothing, thanks.': require('../assets/audio/nothing-thanks-67bb4543.m4a'),
  'There\'s something I never told you. Can I show you tomorrow?': require('../assets/audio/there-s-something-i-never-told-you-can-i-525805bf.m4a'),
  'Sure, I\'ll be there.': require('../assets/audio/sure-i-ll-be-there-c62eef45.m4a'),
  'It\'s a gift.': require('../assets/audio/it-s-a-gift-917f0a47.m4a'),
  'Morning! Ready to see my surprise?': require('../assets/audio/morning-ready-to-see-my-surprise-fee30027.m4a'),
  'I\'m getting ready, let\'s go!': require('../assets/audio/i-m-getting-ready-let-s-go-b874f3eb.m4a'),
  'Not now.': require('../assets/audio/not-now-b99179e6.m4a'),
  'We\'ll take the streetcar. It\'s not far.': require('../assets/audio/we-ll-take-the-streetcar-it-s-not-far-2ddfff37.m4a'),
  'Sounds fun, I love streetcars.': require('../assets/audio/sounds-fun-i-love-streetcars-6715d996.m4a'),
  'Here\'s our stop!': require('../assets/audio/here-s-our-stop-1db5567b.m4a'),
  'Perfect, let\'s get off.': require('../assets/audio/perfect-let-s-get-off-d619cae6.m4a'),
  'Already?': require('../assets/audio/already-1fb6abae.m4a'),
  'This is it. I opened it last spring.': require('../assets/audio/this-is-it-i-opened-it-last-spring-aae5d43d.m4a'),
  'Wow, you own this place?': require('../assets/audio/wow-you-own-this-place-25f24ccc.m4a'),
  'I don\'t like books.': require('../assets/audio/i-don-t-like-books-594e2580.m4a'),
  'I named it after the letters we wrote as kids.': require('../assets/audio/i-named-it-after-the-letters-we-wrote-as-b97cc04e.m4a'),
  'That\'s so sweet.': require('../assets/audio/that-s-so-sweet-b01617b0.m4a'),
  'That\'s strange.': require('../assets/audio/that-s-strange-641c8a1e.m4a'),
  'Come in — the first book is on me.': require('../assets/audio/come-in-the-first-book-is-on-me-c1248460.m4a'),
  'Thank you, Emma.': require('../assets/audio/thank-you-emma-331ff3ae.m4a'),
  'No, I\'m leaving.': require('../assets/audio/no-i-m-leaving-f4564d34.m4a'),
  'Excuse me, is this... for an old friend?': require('../assets/audio/excuse-me-is-this-for-an-old-friend-b6f886bb.m4a'),
  'Yes, that\'s me.': require('../assets/audio/yes-that-s-me-a22bfbd0.m4a'),
  'No idea.': require('../assets/audio/no-idea-95db6d1a.m4a'),
  'Another letter? Who could this be from?': require('../assets/audio/another-letter-who-could-this-be-from-7c1090df.m4a'),
  'Let\'s open it together.': require('../assets/audio/let-s-open-it-together-173454ef.m4a'),
  'Throw it away.': require('../assets/audio/throw-it-away-5707961c.m4a'),
  'To be continued...': require('../assets/audio/to-be-continued-1f388239.m4a'),
  'I can\'t wait for the next chapter.': require('../assets/audio/i-can-t-wait-for-the-next-chapter-e0b10484.m4a'),
  'The end.': require('../assets/audio/the-end-6784afa2.m4a'),
};
