// PORTED from a-decade-apart/content/chapter1.js..chapter94.js — the full 94-chapter
// storyline, mechanically merged (same field names/shape, typed via GameContent) and
// generated by replaying the chapter*.js files (each one does
// GAME_CONTENT.scenes.push(...) / vocabBank.push(...) / Object.assign(skillMeta, ...))
// in a sandboxed VM in chapter order, matching exactly what index.html does at runtime
// by loading all 94 <script> tags before main.js.
//
// The data itself lives in ./game-content.json rather than as an inline TS object
// literal: with 938 scenes (~3 nodes each, choices, vocabBank of 3871 entries) TS's
// own type-checker chokes on an object literal this large ("TS2590: union type too
// complex to represent") — a JSON import sidesteps that checking path entirely.
//
// A handful of scene.transition lines for chapter 1 (taxi-ride, hostel-checkin,
// corner-cafe, asking-directions, cn-tower, reunion-dinner, bookstore-reveal,
// new-envelope) were hand-authored for the mobile app specifically (the web source
// doesn't have them) and are already baked into game-content.json — re-apply them
// after any future re-merge from the web source.
import type { GameContent } from '@/lib/game/types';

import rawContent from './game-content.json';

export const GAME_CONTENT = rawContent as unknown as GameContent;
